disabled_rules:
  - trailing_whitespace
  - todo
  - force_cast
  - force_unwrapping
  
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - sorted_imports
  - vertical_parameter_alignment_on_call

included:
  - RoutineX

excluded:
  - RoutineXTests
  - RoutineXUITests

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100
type_body_length:
  warning: 300
  error: 500
  
reporter: "xcode"
